### PR TITLE
Some code optimizations

### PR DESCRIPTION
**Pull request by erommel**
stripe-handler.js optimized
Optimized function that generates options for <select> tag

These changes are optional, but recommended since it makes the code more clear.

### CODE REVIEW

**Comment by erommel** [comment]
Apparently, "Optimized function that generates options for <select> tag" commit has a bug that won't let the shortcode inserter operate properly. I'll provide a fix for this after I get up, so please don't release this version to production yet.

**Comment by Arsenal21** [comment]
okay I have reverted the commits. The currently released version of the plugin has no bugs (as far as I can see). So lets not worry about it for now unless you think this will be a huge improvement.

**Comment by erommel** [comment]
Ok, cool. Let it stay like that for now, it should be working fine.

**Comment by erommel** [comment]
Though you can re-commit this one 68539f0bf38c728468386983c74938cfb8965e61 as it's working just fine and makes JS code clearer ;-)

**Pull request merged**
